# @Author: GeorgeRaven <archer>
# @Date:   2020-10-19T10:53:35+01:00
# @Last modified by:   archer
# @Last modified time: 2020-10-19T10:57:47+01:00
# @License: please see LICENSE file in project root

version: "3.7"

services:
  sync:
    build:
      context: ./.
      dockerfile: Dockerfile
    container_name: archer/stress
    command:
      - "-h"
    restart: never
    # this allows you to connect to local ports say localhost or 127.0.0.1
    network_mode: "host"
