# @Author: GeorgeRaven <archer>
# @Date:   2020-10-19T10:53:35+01:00
# @Last modified by:   archer
# @Last modified time: 2021-04-21T16:21:09+01:00
# @License: please see LICENSE file in project root

version: "3.7"

services:
  sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrape
    command:
      - "-h"
    # this allows you to connect to local ports say localhost or 127.0.0.1
    network_mode: "host"
