# @Author: GeorgeRaven <archer>
# @Date:   2020-10-19T10:53:35+01:00
# @Last modified by:   archer
# @Last modified time: 2020-10-19T10:57:47+01:00
# @License: please see LICENSE file in project root

version: "3.7"

services:
  sync:
    env_file:
      - "./sync/.env"
    build:
      context: ./sync/
      dockerfile: Dockerfile
    container_name: sync-container
    restart: always
    volumes:
      - "./sync:/sync"
    network_mode: "host"

# networks:
#   hostnet:
#     external: true
#     name: host
